### ISSUE TITLE
当用一个view addsubview dropdown 弹出来的列表是不可以滑动的

### ISSUE THREAD

**Issue by hongyu315** [Zirkfied/ZFDropDown#2]
[self.inputUILayout addSubview:self.dropDown];

后弹出来的tableview列表是不可以滑动的

**Comment by Zirkfied** [comment]
你返回显示多少行？

**Comment by hongyu315** [comment]
试过5、6、10行都不行 如果直接用self.view addSubview 是可以的

**Comment by hongyu315** [comment]
self.dropDown2 = [[ZFDropDown alloc] initWithFrame:CGRectMake(0, 0 , width, height) pattern:kDropDownPatternDefault];
    self.dropDown2.delegate = self;
    [self.dropDown2.topicButton setTitle:@"中国大陆" forState:UIControlStateNormal];
    self.dropDown2.topicButton.titleLabel.font = [UIFont systemFontOfSize:17.f];
    self.dropDown2.borderStyle = kDropDownTopicBorderStyleSingleLine;
    self.dropDown2.separatorStyle = UITableViewCellSeparatorStyleSingleLine;
    self.dropDown2.cellTextFont = [UIFont boldSystemFontOfSize:20.f];
    
    UIView *cview = [[UIView alloc] initWithFrame:CGRectMake(xPos, yPos + 350, 300, 100)];
    [cview addSubview:self.dropDown2];
//    [self.view addSubview:self.dropDown2];
    [self.view addSubview:cview];
    
    
    self.tap = [[ZFTapGestureRecognizer alloc] initWithTarget:self action:@selector(tapAction)];
    [self.view addGestureRecognizer:self.tap];

**Comment by hongyu315** [comment]
在外面套一层view后遇到的问题是列表不能滑动和点击事件无法触发，应该是手势事件冲突了，我还没改好

**Comment by hongyu315** [comment]
/**
 *  重写手势代理方法（添加了手势导致tableView的didSelectRowAtIndexPath方法失效）
 */
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch{
    
    if ([NSStringFromClass([touch.view class]) isEqualToString:@"UITableViewCellContentView"]) {
        NSLog(@"11");

        return NO;
    }
    
    if ([NSStringFromClass([touch.view class]) isEqualToString:@"UIView"]) {
        NSLog(@"22");

        return NO;
    }
    
    NSLog(@"33");
    return YES;
}

**Comment by Zirkfied** [comment]
现在好了吗？

**Comment by hongyu315** [comment]
没

**Comment by hongyu315** [comment]
@Zirkfied 大神帮忙看看 为什么套一层view 就无法滑动和无法接受到点击事件？

**Comment by hongyu315** [comment]
问题已经解决了，是因为我另外一层view的高度设置的太矮了，虽然列表可以展现，但是点击下滑都不行。
解决方法是套的那层view高度要大于展现出来的tableview的高度才能滑动。

**Comment by Zirkfied** [comment]
解决就好
